server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/todo_users
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: salsob7y@gmail.com
    password: fbij uoqh jccp eaww
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
